const livros = [
  {
    id: 1,
    titulo: 'O Senhor dos Anéis - Volume Único',
    autor: 'J. R. R. Tolkien',
    paginas: 987,
    categoria: 'Fantasia',
    recomenda: true,
    leu: true,
  },
  {
    id: 2,
    titulo: 'O Silmarillion',
    autor: 'J. R. R. Tolkien',
    paginas: 487,
    categoria: 'Fantasia',
    recomenda: true,
    leu: true,
  },
  {
    id: 3,
    titulo: 'A simples arte de ligar o F*da-se',
    autor: 'Alguem ai',
    paginas: 20,
    categoria: 'Autoajuda',
    recomenda: false,
    leu: false,
  },
  {
    id: 4,
    titulo: 'Guia de Raças Caninas',
    autor: 'CBKC',
    paginas: 25,
    categoria: 'Animais',
    recomenda: true,
    leu: false,
  },
  {
    id: 5,
    titulo: 'Hogwarts - Uma História',
    autor: 'Batilda Bagshot',
    paginas: 800,
    categoria: 'História',
    recomenda: true,
    leu: false,
  },
  {
    id: 6,
    titulo: 'Meu eu mágico',
    autor: 'Gilderoy Lockhart',
    paginas: 100,
    categoria: 'Biografia',
    recomenda: false,
    leu: false,
  },
  {
    id: 7,
    titulo: 'Padrões JavaScript',
    autor: 'Stoyan Stefanov',
    paginas: 200,
    categoria: 'Tecnologia',
    recomenda: true,
    leu: false,
  },
]

module.exports = livros;